all check:
	@# SC1091:
	@# In build-swift.sh line 6:
	@# source SwiftVersion.mk
	@# ^-- SC1091: Not following: SwiftVersion.mk was not specified as input (see shellcheck -x).
	shellcheck *.sh -e 1091
