// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text;
using Foundation;
using UIKit;
using SwiftPigLatinLibrary;
using SwiftRuntimeLibrary;

namespace PigLatin {
        public partial class MainViewController : UIViewController {
                public MainViewController (IntPtr handle) : base (handle)
                {
                }

                public override void ViewDidLoad ()
                {
                        base.ViewDidLoad ();
                        this.XlateButton.TouchUpInside += (sender, e) => {
                                var inputText = InputText.Text;

                                var sb = new StringBuilder ();
                                using (var igpay = new IgPay (SwiftString.FromString (inputText))) {
                                        for (int i = 0; i < igpay.Count; i++) {
                                                if (i > 0)
                                                        sb.Append (" ");
                                                sb.Append (igpay [i].ToString ());
                                        }
                                }

                                var outputText = sb.ToString ();
                                this.OuputText.Text = outputText;
                        };
                }
        }
}
