// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by symbolicator.csx
// You can add constants to this file as needed,
// just make sure you follow this convention for the name:
// '<Type|Interface>_<type>' e.g. 'ISwiftComparable_nuint'.

using System;

namespace SwiftRuntimeLibrary {

	internal static class SwiftCoreConstants {

		internal const string LibSwiftCore = "libswiftCore.dylib";

		// ISwiftComparable Constants
		internal const string ISwiftComparable_SwiftString = "$sSSSLsWP";
		internal const string ISwiftComparable_IntPtr = "$sSVSLsWP";
		internal const string ISwiftComparable_double = "$sSdSLsWP";
		internal const string ISwiftComparable_float = "$sSfSLsWP";
		internal const string ISwiftComparable_nint = "$sSiSLsWP";
		internal const string ISwiftComparable_nuint = "$sSuSLsWP";
		internal const string ISwiftComparable_sbyte = "$ss4Int8VSLsWP";
		internal const string ISwiftComparable_short = "$ss5Int16VSLsWP";
		internal const string ISwiftComparable_int = "$ss5Int32VSLsWP";
		internal const string ISwiftComparable_long = "$ss5Int64VSLsWP";
		internal const string ISwiftComparable_byte = "$ss5UInt8VSLsWP";
		internal const string ISwiftComparable_ushort = "$ss6UInt16VSLsWP";
		internal const string ISwiftComparable_uint = "$ss6UInt32VSLsWP";
		internal const string ISwiftComparable_ulong = "$ss6UInt64VSLsWP";
		internal const string ISwiftComparable_ProtocolDescriptor = "$sSLMp";

		// ISwiftEquatable Constants
		internal const string ISwiftEquatable_SwiftString = "$sSSSQsWP";
		internal const string ISwiftEquatable_IntPtr = "$sSVSQsWP";
		internal const string ISwiftEquatable_bool = "$sSbSQsWP";
		internal const string ISwiftEquatable_double = "$sSdSQsWP";
		internal const string ISwiftEquatable_float = "$sSfSQsWP";
		internal const string ISwiftEquatable_nint = "$sSiSQsWP";
		internal const string ISwiftEquatable_nuint = "$sSuSQsWP";
		internal const string ISwiftEquatable_sbyte = "$ss4Int8VSQsWP";
		internal const string ISwiftEquatable_short = "$ss5Int16VSQsWP";
		internal const string ISwiftEquatable_int = "$ss5Int32VSQsWP";
		internal const string ISwiftEquatable_long = "$ss5Int64VSQsWP";
		internal const string ISwiftEquatable_byte = "$ss5UInt8VSQsWP";
		internal const string ISwiftEquatable_ushort = "$ss6UInt16VSQsWP";
		internal const string ISwiftEquatable_uint = "$ss6UInt32VSQsWP";
		internal const string ISwiftEquatable_ulong = "$ss6UInt64VSQsWP";
		internal const string ISwiftEquatable_ProtocolDescriptor = "$sSQMp";

		// ISwiftHashable Constants
		internal const string ISwiftHashable_SwiftString = "$sSSSHsWP";
		internal const string ISwiftHashable_IntPtr = "$sSVSHsWP";
		internal const string ISwiftHashable_bool = "$sSbSHsWP";
		internal const string ISwiftHashable_double = "$sSdSHsWP";
		internal const string ISwiftHashable_float = "$sSfSHsWP";
		internal const string ISwiftHashable_nint = "$sSiSHsWP";
		internal const string ISwiftHashable_nuint = "$sSuSHsWP";
		internal const string ISwiftHashable_sbyte = "$ss4Int8VSHsWP";
		internal const string ISwiftHashable_short = "$ss5Int16VSHsWP";
		internal const string ISwiftHashable_int = "$ss5Int32VSHsWP";
		internal const string ISwiftHashable_long = "$ss5Int64VSHsWP";
		internal const string ISwiftHashable_byte = "$ss5UInt8VSHsWP";
		internal const string ISwiftHashable_ushort = "$ss6UInt16VSHsWP";
		internal const string ISwiftHashable_uint = "$ss6UInt32VSHsWP";
		internal const string ISwiftHashable_ulong = "$ss6UInt64VSHsWP";
		internal const string ISwiftHashable_ProtocolDescriptor = "$sSHMp";

		// UnsafePointer Constants
		internal const string UnsafePointer_NominalTypeDescriptor = "$sSPMn";

		// UnsafeMutablePointer Constants
		internal const string UnsafeMutablePointer_NominalTypeDescriptor = "$sSpMn";

		// NativeMethodsForUnsafeMutablePointer Constants
		internal const string NativeMethodsForUnsafeMutablePointer_Metatype = "$sSpMn";
		internal const string NativeMethodsForUnsafeMutablePointer_Initialize = "$sSp10initialize2to5countyx_SitF";
		internal const string NativeMethodsForUnsafeMutablePointer_Deinitialize = "$sSp12deinitialize5countSvSi_tF";
		internal const string NativeMethodsForUnsafeMutablePointer_Deallocate = "$sSp10deallocate8capacityySi_tF";

		// SwiftString Constants
		internal const string SwiftString_NominalTypeDescriptor = "$sSSMn";
		[SymbolicatorInfo (Skip = true)]
		internal const string SwiftString_Metadata = "$sSSN";

		// SwiftSet Constants
		internal const string SwiftSet_NominalTypeDescriptor = "$sShMn";
		internal const string SwiftSet_PIMetadataAccessor = "$sShMa";

		// SwiftOptional Constants
		internal const string SwiftOptional_NominalTypeDescriptor = "$sSqMn";
		internal const string SwiftOptional_PIMetadataAccessor = "$sSqMa";

		// SwiftDictionary Constants
		internal const string SwiftDictionary_NominalTypeDescriptor = "$sSDMn";
		internal const string SwiftDictionary_PIMetadataAccessor = "$sSDMa";

		// SwiftCharacter Constants
		internal const string SwiftCharacter_NominalTypeDescriptor = "$sSJMn";
		[SymbolicatorInfo (Skip = true)]
		internal const string SwiftCharacter_Metadata = "$sSJN";

		// SwiftArray Constants
		internal const string SwiftArray_NominalTypeDescriptor = "$sSaMn";
		internal const string SwiftArray_PIMetadataAccessor = "$sSaMa";
		internal const string SwiftArray_CTor = "$sS2ayxGycfC";

		// OpaquePointer Constants
		internal const string OpaquePointer_NominalTypeDescriptor = "$sSPMn";
		[SymbolicatorInfo (Skip = true)]
		internal const string OpaquePointer_Metadata = "$ss13OpaquePointerVN";

		// ICustomStringConvertible Constants
		[SymbolicatorInfo (Skip = true)]
		internal const string ICustomStringConvertible_MetadataAccessor = "$s7XamGlue21xam_proxy_ConvertibleCMa";
		internal const string ICustomStringConvertible_ProtocolDescriptor = "$ss23CustomStringConvertibleMp";

		// UnsafeRawBufferPointer Contants
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointer_MetadataAccessor = "$sSWMa";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointer_Metadata = "$sSWN";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointer_NominalTypeDescriptor = "$sSWMn";

		// UnsafeMutableRawBufferPointer Contants
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointer_MetadataAccessor = "$sSwMa";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointer_Metadata = "$sSwN";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointer_NominalTypeDescriptor = "$sSwMn";

		// Hasher Constants
		[SymbolicatorInfo (Skip = true)]
		internal const string Hasher_MetadataAccessor = "$ss6HasherVMa";
		[SymbolicatorInfo (Skip = true)]
		internal const string Hasher_Metadata = "$ss6HasherV5_CoreVN";
		[SymbolicatorInfo (Skip = true)]
		internal const string Hasher_NominalTypeDescriptor = "$ss6HasherVMn";

	}
}

