// Code generated by symbolicator.csx
// You can add constants to this file as needed,
// just make sure you follow this convention for the name:
// '<Type|Interface>_<type>' e.g. 'ISwiftComparable_nuint'.

using System;

namespace SwiftRuntimeLibrary {

	internal static class XamGlueConstants {

		// ISwiftComparable Constants
		internal const string ISwiftComparable_MetadataAccessor = "$s7XamGlue13EveryProtocolCMa";

		// ISwiftEquatable Constants
		internal const string ISwiftEquatable_MetadataAccessor = "$s7XamGlue13EveryProtocolCMa";

		// ISwiftHashable Constants
		internal const string ISwiftHashable_MetadataAccessor = "$s7XamGlue13EveryProtocolCMa";

		// BlindClosureMapper Constants
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A>(a1: (A) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<A>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapA = "$s7XamGlue20swiftClosureToAction2a1SpyySpyxGcGyxc_tlF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B>(a1: (A, B) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapAB = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_tGcGyx_q_tc_tr0_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C>(a1: (A, B, C) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABC = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_tGcGyx_q_q0_tc_tr1_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D>(a1: (A, B, C, D) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCD = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_tGcGyx_q_q0_q1_tc_tr2_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E>(a1: (A, B, C, D, E) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDE = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_tGcGyx_q_q0_q1_q2_tc_tr3_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F>(a1: (A, B, C, D, E, F) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEF = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_tGcGyx_q_q0_q1_q2_q3_tc_tr4_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G>(a1: (A, B, C, D, E, F, G) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFG = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_tGcGyx_q_q0_q1_q2_q3_q4_tc_tr5_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H>(a1: (A, B, C, D, E, F, G, H) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGH = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_tGcGyx_q_q0_q1_q2_q3_q4_q5_tc_tr6_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I>(a1: (A, B, C, D, E, F, G, H, I) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHI = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_tc_tr7_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J>(a1: (A, B, C, D, E, F, G, H, I, J) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJ = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tc_tr8_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K>(a1: (A, B, C, D, E, F, G, H, I, J, K) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJK = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tc_tr9_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K, L>(a1: (A, B, C, D, E, F, G, H, I, J, K, L) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJKL = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tc_tr10_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K, L, M>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJKLM = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tc_tr11_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJKLMN = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tc_tr12_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJKLMNO = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tc_tr13_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToAction<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> ()) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)>) -> ()>")]
		internal const string BlindClosureMapper_ActionMapABCDEFGHIJKLMNOP = "$s7XamGlue20swiftClosureToAction2a1SpyySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGcGyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tc_tr14_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A>(a1: () -> A) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<A>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapA = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyxGcGxyc_tlF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B>(a1: (A) -> B) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<B>, Swift.UnsafeMutablePointer<A>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapAB = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq_G_SpyxGtcGq_xc_tr0_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C>(a1: (A, B) -> C) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<C>, Swift.UnsafeMutablePointer<(A, B)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABC = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq0_G_Spyx_q_tGtcGq0_x_q_tc_tr1_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D>(a1: (A, B, C) -> D) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<D>, Swift.UnsafeMutablePointer<(A, B, C)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCD = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq1_G_Spyx_q_q0_tGtcGq1_x_q_q0_tc_tr2_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E>(a1: (A, B, C, D) -> E) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<E>, Swift.UnsafeMutablePointer<(A, B, C, D)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDE = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq2_G_Spyx_q_q0_q1_tGtcGq2_x_q_q0_q1_tc_tr3_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F>(a1: (A, B, C, D, E) -> F) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<F>, Swift.UnsafeMutablePointer<(A, B, C, D, E)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEF = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq3_G_Spyx_q_q0_q1_q2_tGtcGq3_x_q_q0_q1_q2_tc_tr4_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G>(a1: (A, B, C, D, E, F) -> G) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<G>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFG = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq4_G_Spyx_q_q0_q1_q2_q3_tGtcGq4_x_q_q0_q1_q2_q3_tc_tr5_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H>(a1: (A, B, C, D, E, F, G) -> H) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<H>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGH = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq5_G_Spyx_q_q0_q1_q2_q3_q4_tGtcGq5_x_q_q0_q1_q2_q3_q4_tc_tr6_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I>(a1: (A, B, C, D, E, F, G, H) -> I) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<I>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHI = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq6_G_Spyx_q_q0_q1_q2_q3_q4_q5_tGtcGq6_x_q_q0_q1_q2_q3_q4_q5_tc_tr7_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J>(a1: (A, B, C, D, E, F, G, H, I) -> J) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<J>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJ = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq7_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_tGtcGq7_x_q_q0_q1_q2_q3_q4_q5_q6_tc_tr8_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K>(a1: (A, B, C, D, E, F, G, H, I, J) -> K) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<K>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJK = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq8_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGtcGq8_x_q_q0_q1_q2_q3_q4_q5_q6_q7_tc_tr9_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L>(a1: (A, B, C, D, E, F, G, H, I, J, K) -> L) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<L>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKL = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq9_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGtcGq9_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tc_tr10_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L, M>(a1: (A, B, C, D, E, F, G, H, I, J, K, L) -> M) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<M>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKLM = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq10_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGtcGq10_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tc_tr11_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M) -> N) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<N>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKLMN = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq11_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGtcGq11_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tc_tr12_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<O>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKLMNO = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq12_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGtcGq12_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tc_tr13_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<P>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKLMNOP = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq13_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGtcGq13_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tc_tr14_lF";
		[SymbolicatorInfo ("XamGlue.swiftClosureToFunc<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(a1: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q) -> Swift.UnsafeMutablePointer<(Swift.UnsafeMutablePointer<Q>, Swift.UnsafeMutablePointer<(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)>) -> ()>")]
		internal const string BlindClosureMapper_FuncMapABCDEFGHIJKLMNOPQ = "$s7XamGlue18swiftClosureToFunc2a1SpyySpyq14_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGtcGq14_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tc_tr15_lF";

		// NativeMethodsForXamTrivialSwiftObject Constants
		internal const string NativeMethodsForXamTrivialSwiftObject_PIdtor = "$s7XamGlue0A18TrivialSwiftObjectCfD";
		internal const string NativeMethodsForXamTrivialSwiftObject_PIctor = "$s7XamGlue0A18TrivialSwiftObjectCACycfC";
		internal const string NativeMethodsForXamTrivialSwiftObject_PImeta = "$s7XamGlue0A18TrivialSwiftObjectCMa";

		// NativeMethodsForUnsafeMutablePointer Constants
		internal const string NativeMethodsForUnsafeMutablePointer_Allocate = "$s7XamGlue28allocateUnsafeMutablePointer6retval8capacityySpySpyxGG_SitlF";
		internal const string NativeMethodsForUnsafeMutablePointer_Get = "$s7XamGlue30getPointeeUnsafeMutablePointer6retval1pySpyxG_AEtlF";
		internal const string NativeMethodsForUnsafeMutablePointer_Set = "$s7XamGlue30setPointeeUnsafeMutablePointer1p3valySpyxG_AEtlF";
		internal const string NativeMethodsForUnsafeMutablePointer_Advance = "$s7XamGlue27advanceUnsafeMutablePointer6retval1p2byySpySpyxGG_AFSitlF";

		// SwiftString Constants
		internal const string SwiftString_FromUTF16Pointer = "$s7XamGlue21fromUnmanagedUTF16Raw5start18numberOfCodePoints6resultySPys6UInt16VG_SiSpySSGtF";
		internal const string SwiftString_FromUTF8Pointer = "$s7XamGlue8fromUTF84data6resultySPys4Int8VG_SpySSGtF";
		internal const string SwiftString_UTF8StringSize = "$s7XamGlue14UTF8StringSize1sSiSpySSG_tF";
		internal const string SwiftString_CopyStringToUTF8Buffer = "$s7XamGlue22copyStringToUTF8Buffer4data1sySpys5UInt8VG_SpySSGtF";

		// SwiftSet Constants
		internal const string SwiftSet_NewSet = "$s7XamGlue6newSet6retval8capacityySpyShyxGG_SitSHRzlF";
		internal const string SwiftSet_SetGetCount = "$s7XamGlue11setGetCount1sSiSpyShyxGG_tSHRzlF";
		internal const string SwiftSet_SetIsEmpty = "$s7XamGlue10setIsEmpty1sSbSpyShyxGG_tSHRzlF";
		internal const string SwiftSet_SetGetCapacity = "$s7XamGlue14setGetCapacity1sSiSpyShyxGG_tSHRzlF";
		internal const string SwiftSet_SetContains = "$s7XamGlue11setContains1s1eSbSpyShyxGG_SPyxGtSHRzlF";
		internal const string SwiftSet_SetInsert = "$s7XamGlue9setInsert6retval1s1eySpySb_xtG_SpyShyxGGSPyxGtSHRzlF";
		internal const string SwiftSet_SetRemove = "$s7XamGlue9setRemove6retval1s1eySpyxSgG_SpyShyxGGSPyxGtSHRzlF";

		// NativeMethodsForSwiftOptional Constants
		internal const string NativeMethodsForSwiftOptional_NewNone = "$s7XamGlue15optionalNewNone6retvalySpyxSgG_tlF";
		internal const string NativeMethodsForSwiftOptional_NewSome = "$s7XamGlue15optionalNewSome6retval3valySpyxSgG_SPyxGtlF";
		internal const string NativeMethodsForSwiftOptional_HasValue = "$s7XamGlue16optionalHasValue3valSbSpyxSgG_tlF";
		internal const string NativeMethodsForSwiftOptional_Case = "$s7XamGlue12optionalCase3valSiSpyxSgG_tlF";
		internal const string NativeMethodsForSwiftOptional_Value = "$s7XamGlue13optionalValue6optval3valySpyxSgG_SpyxGtlF";

		// SwiftError Constants
		internal const string SwiftError_GetErrorDescription = "$s7XamGlue19getErrorDescription7message5errorySpySSG_s0D0_ptF";
		internal const string SwiftError_DotNetErrorFactory = "$s7XamGlue15makeDotNetError7message9classNames0F0_pSPySSG_AFtF";

		// SwiftEquatableProxy Constants
		internal const string SwiftEquatableProxy_PISetVtable = "$s7XamGlue23setEquatable_xam_vtable3uvtySV_tF";

		// SwiftDotNetCapsule Constants
		internal const string SwiftDotNetCapsule_AllocCapsule = "$s7XamGlue17makeDotNetCapsule1pAA0deF0Cs13OpaquePointerV_tF";
		internal const string SwiftDotNetCapsule_GetData = "$s7XamGlue14getCapsuleData3dncs13OpaquePointerVAA06DotNetD0C_tF";
		internal const string SwiftDotNetCapsule_SetData = "$s7XamGlue14setCapsuleData3dnc1pyAA06DotNetD0C_s13OpaquePointerVtF";
		internal const string SwiftDotNetCapsule_SetCapsuleOnDeinit = "$s7XamGlue20setCapsuleDeinitFunc1pyySVXC_tF";

		// SwiftDictionary Constants
		internal const string SwiftDictionary_NewDict = "$s7XamGlue7newDict6retval8capacityySpySDyxq_GG_SitSHRzr0_lF";
		internal const string SwiftDictionary_DictCount = "$s7XamGlue9dictCount1dSiSpySDyxq_GG_tSHRzr0_lF";
		internal const string SwiftDictionary_DictKeys = "$s7XamGlue8dictKeys6retval1dySpySayxGG_SpySDyxq_GGtSHRzr0_lF";
		internal const string SwiftDictionary_DictValues = "$s7XamGlue10dictValues6retval1dySpySayq_GG_SpySDyxq_GGtSHRzr0_lF";
		internal const string SwiftDictionary_DictContainsKey = "$s7XamGlue15dictContainsKey1d3keySbSpySDyxq_GG_xtSHRzr0_lF";
		internal const string SwiftDictionary_DictClear = "$s7XamGlue9dictClear1dySpySDyxq_GG_tSHRzr0_lF";
		internal const string SwiftDictionary_DictRemove = "$s7XamGlue10dictRemove1d3keySbSpySDyxq_GG_xtSHRzr0_lF";
		internal const string SwiftDictionary_DictSet = "$s7XamGlue7dictSet1d3key3valySpySDyxq_GG_xq_tSHRzr0_lF";
		internal const string SwiftDictionary_DictGet = "$s7XamGlue7dictGet6retval1d3keyySpyq__SbtG_SpySDyxq_GGxtSHRzr0_lF";

		// SwiftCore Constants
		internal const string SwiftCore_swiftsizeof = "$s7XamGlue6sizeofySixlF";
		internal const string SwiftCore_swiftstrideof = "$s7XamGlue8strideofySixlF";
		internal const string SwiftCore_swiftalignmentof = "$s7XamGlue11alignmentofySixlF";
		internal const string SwiftCore_SwiftErrorMetatype = "$s7XamGlue13errorMetadataypXpyF";
		internal const string SwiftCore_ActionToSwiftClosure1 = "$s7XamGlue23netActionToSwiftClosure2a1yxcySpyxGc_tlF";
		internal const string SwiftCore_ActionToSwiftClosure2 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_tcySpyx_q_tGc_tr0_lF";
		internal const string SwiftCore_ActionToSwiftClosure3 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_tcySpyx_q_q0_tGc_tr1_lF";
		internal const string SwiftCore_ActionToSwiftClosure4 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_tcySpyx_q_q0_q1_tGc_tr2_lF";
		internal const string SwiftCore_ActionToSwiftClosure5 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_tcySpyx_q_q0_q1_q2_tGc_tr3_lF";
		internal const string SwiftCore_ActionToSwiftClosure6 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_tcySpyx_q_q0_q1_q2_q3_tGc_tr4_lF";
		internal const string SwiftCore_ActionToSwiftClosure7 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_tcySpyx_q_q0_q1_q2_q3_q4_tGc_tr5_lF";
		internal const string SwiftCore_ActionToSwiftClosure8 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_tcySpyx_q_q0_q1_q2_q3_q4_q5_tGc_tr6_lF";
		internal const string SwiftCore_ActionToSwiftClosure9 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_tGc_tr7_lF";
		internal const string SwiftCore_ActionToSwiftClosure10 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGc_tr8_lF";
		internal const string SwiftCore_ActionToSwiftClosure11 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGc_tr9_lF";
		internal const string SwiftCore_ActionToSwiftClosure12 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGc_tr10_lF";
		internal const string SwiftCore_ActionToSwiftClosure13 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGc_tr11_lF";
		internal const string SwiftCore_ActionToSwiftClosure14 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGc_tr12_lF";
		internal const string SwiftCore_ActionToSwiftClosure15 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGc_tr13_lF";
		internal const string SwiftCore_ActionToSwiftClosure16 = "$s7XamGlue23netActionToSwiftClosure2a1yx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tcySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGc_tr14_lF";
		internal const string SwiftCore_FuncToSwiftClosure1 = "$s7XamGlue21netFuncToSwiftClosure2a1xycySpyxGc_tlF";
		internal const string SwiftCore_FuncToSwiftClosure2 = "$s7XamGlue21netFuncToSwiftClosure2a1q_xcySpyq_G_SpyxGtc_tr0_lF";
		internal const string SwiftCore_FuncToSwiftClosure3 = "$s7XamGlue21netFuncToSwiftClosure2a1q0_x_q_tcySpyq0_G_Spyx_q_tGtc_tr1_lF";
		internal const string SwiftCore_FuncToSwiftClosure4 = "$s7XamGlue21netFuncToSwiftClosure2a1q1_x_q_q0_tcySpyq1_G_Spyx_q_q0_tGtc_tr2_lF";
		internal const string SwiftCore_FuncToSwiftClosure5 = "$s7XamGlue21netFuncToSwiftClosure2a1q2_x_q_q0_q1_tcySpyq2_G_Spyx_q_q0_q1_tGtc_tr3_lF";
		internal const string SwiftCore_FuncToSwiftClosure6 = "$s7XamGlue21netFuncToSwiftClosure2a1q3_x_q_q0_q1_q2_tcySpyq3_G_Spyx_q_q0_q1_q2_tGtc_tr4_lF";
		internal const string SwiftCore_FuncToSwiftClosure7 = "$s7XamGlue21netFuncToSwiftClosure2a1q4_x_q_q0_q1_q2_q3_tcySpyq4_G_Spyx_q_q0_q1_q2_q3_tGtc_tr5_lF";
		internal const string SwiftCore_FuncToSwiftClosure8 = "$s7XamGlue21netFuncToSwiftClosure2a1q5_x_q_q0_q1_q2_q3_q4_tcySpyq5_G_Spyx_q_q0_q1_q2_q3_q4_tGtc_tr6_lF";
		internal const string SwiftCore_FuncToSwiftClosure9 = "$s7XamGlue21netFuncToSwiftClosure2a1q6_x_q_q0_q1_q2_q3_q4_q5_tcySpyq6_G_Spyx_q_q0_q1_q2_q3_q4_q5_tGtc_tr7_lF";
		internal const string SwiftCore_FuncToSwiftClosure10 = "$s7XamGlue21netFuncToSwiftClosure2a1q7_x_q_q0_q1_q2_q3_q4_q5_q6_tcySpyq7_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_tGtc_tr8_lF";
		internal const string SwiftCore_FuncToSwiftClosure11 = "$s7XamGlue21netFuncToSwiftClosure2a1q8_x_q_q0_q1_q2_q3_q4_q5_q6_q7_tcySpyq8_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGtc_tr9_lF";
		internal const string SwiftCore_FuncToSwiftClosure12 = "$s7XamGlue21netFuncToSwiftClosure2a1q9_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tcySpyq9_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGtc_tr10_lF";
		internal const string SwiftCore_FuncToSwiftClosure13 = "$s7XamGlue21netFuncToSwiftClosure2a1q10_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tcySpyq10_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGtc_tr11_lF";
		internal const string SwiftCore_FuncToSwiftClosure14 = "$s7XamGlue21netFuncToSwiftClosure2a1q11_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tcySpyq11_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGtc_tr12_lF";
		internal const string SwiftCore_FuncToSwiftClosure15 = "$s7XamGlue21netFuncToSwiftClosure2a1q12_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tcySpyq12_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGtc_tr13_lF";
		internal const string SwiftCore_FuncToSwiftClosure16 = "$s7XamGlue21netFuncToSwiftClosure2a1q13_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tcySpyq13_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGtc_tr14_lF";
		internal const string SwiftCore_FuncToSwiftClosure17 = "$s7XamGlue21netFuncToSwiftClosure2a1q14_x_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tcySpyq14_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGtc_tr15_lF";

		// SwiftHashableProxy Constants
		internal const string SwiftHashableProxy_PIHashvalue = "$s7XamGlue13EveryProtocolC9hashValueSivg";
		internal const string SwiftHashableProxy_PISetVtable = "$s7XamGlue22setHashable_xam_vtable3uvtySV_tF";

		// SwiftComparableProxy Constants
		internal const string SwiftComparableProxy_PISetVtable = "$s7XamGlue24setComparable_xam_vtable3uvtySV_tF";

		// SwiftCharacter Constants
		internal const string SwiftCharacter_GetCharacterValue = "$s7XamGlue14characterValue1v6resultySpySJG_SpySSGtF";
		internal const string SwiftCharacter_CreateCharacter = "$s7XamGlue15createCharacter3str6resultySpySSG_SpySJGtF";

		// SwiftArray Constants
		internal const string SwiftArray_Count = "$s7XamGlue10arrayCount1aSiSpySayxGG_tlF";
		internal const string SwiftArray_NewArray = "$s7XamGlue8arrayNew8capacitySayxGSi_tlF";
		internal const string SwiftArray_ArrayGet = "$s7XamGlue8arrayGet6retval1a5indexySpyxG_SpySayxGGSitlF";
		internal const string SwiftArray_ArraySet = "$s7XamGlue8arraySet1a5value5indexySpySayxGG_xSitlF";
		internal const string SwiftArray_ArrayClear = "$s7XamGlue10arrayClear1aySpySayxGG_tlF";
		internal const string SwiftArray_ArrayRemoveAt = "$s7XamGlue13arrayRemoveAt1a5indexySpySayxGG_SitlF";
		internal const string SwiftArray_ArrayAdd = "$s7XamGlue8arrayAdd1a5thingySpySayxGG_xtlF";
		internal const string SwiftArray_ArrayInsert = "$s7XamGlue11arrayInsert1a5value5indexySpySayxGG_xSitlF";
		internal const string SwiftArray_ArrayCapacity = "$s7XamGlue13arrayCapacity1aSiSpySayxGG_tlF";

		// SwiftAnyObject Constants
		internal const string SwiftAnyObject_CastAs = "$s7XamGlue6castAs6retval5valueySpyxSgG_yXltlF";

		// ICustomStringConvertible Constants
		internal const string ICustomStringConvertible_ConformanceIdentifier = "$s7XamGlue13EveryProtocolCs23CustomStringConvertibleAAMc";
		internal const string ICustomStringConvertible_NoneDConvertibleGdescription = "$s7XamGlue36xamarin_NoneDConvertibleGdescription6retval4thisySpySSG_s23CustomStringConvertible_pztF";
		internal const string ICustomStringConvertible_SwiftXamSetVtable = "$s7XamGlue25setConvertible_xam_vtable3uvtySV_tF";

		// BlindSwiftClosureRepresentation Constants
		internal const string BlindSwiftClosureRepresentation_InvokePlainAction = "$s7XamGlue17invokePlainAction1fyyyXE_tF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction1 = "$s7XamGlue12invokeAction1f1ayySpyxGXE_AEtlF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction2 = "$s7XamGlue12invokeAction1f1ayySpyx_q_tGXE_AEtr0_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction3 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_tGXE_AEtr1_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction4 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_tGXE_AEtr2_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction5 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_tGXE_AEtr3_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction6 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_tGXE_AEtr4_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction7 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_tGXE_AEtr5_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction8 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_tGXE_AEtr6_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction9 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_tGXE_AEtr7_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction10 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGXE_AEtr8_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction11 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGXE_AEtr9_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction12 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGXE_AEtr10_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction13 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGXE_AEtr11_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction14 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGXE_AEtr12_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction15 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGXE_AEtr13_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeAction16 = "$s7XamGlue12invokeAction1f1ayySpyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGXE_AEtr14_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction1 = "$s7XamGlue14invokeFunction1f6retvalyySpyxGXE_AEtlF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction2 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq_G_SpyxGtXE_AfGtr0_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction3 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq0_G_Spyx_q_tGtXE_AfGtr1_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction4 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq1_G_Spyx_q_q0_tGtXE_AfGtr2_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction5 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq2_G_Spyx_q_q0_q1_tGtXE_AfGtr3_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction6 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq3_G_Spyx_q_q0_q1_q2_tGtXE_AfGtr4_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction7 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq4_G_Spyx_q_q0_q1_q2_q3_tGtXE_AfGtr5_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction8 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq5_G_Spyx_q_q0_q1_q2_q3_q4_tGtXE_AfGtr6_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction9 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq6_G_Spyx_q_q0_q1_q2_q3_q4_q5_tGtXE_AfGtr7_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction10 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq7_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_tGtXE_AfGtr8_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction11 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq8_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_tGtXE_AfGtr9_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction12 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq9_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_tGtXE_AfGtr10_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction13 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq10_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_tGtXE_AfGtr11_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction14 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq11_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_tGtXE_AfGtr12_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction15 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq12_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_tGtXE_AfGtr13_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction16 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq13_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_tGtXE_AfGtr14_lF";
		internal const string BlindSwiftClosureRepresentation_InvokeFunction17 = "$s7XamGlue14invokeFunction1f6retval1ayySpyq14_G_Spyx_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_q12_q13_tGtXE_AfGtr15_lF";

		// UnsafeRawBufferPointer
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointerNew = "$s7XamGlue25unsafeRawBufferPointerNew6retval5start5countySpySWG_SVSitF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointerGetDescription = "$s7XamGlue36unsafeRawBufferPointerGetDescription6retval4thisySpySSG_SpySWGtF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointerGetCount = "$s7XamGlue27unsafeRawBufferPointerCount4thisSiSpySWG_tF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeRawBufferPointerGetAt = "$s7XamGlue27unsafeRawBufferPointerGetAt4this5indexs5UInt8VSpySWG_SitF";

		// UnsafeMutableRawBufferPointer
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointerNew = "$s7XamGlue32unsafeMutableRawBufferPointerNew6retval5start5countySpySwG_SvSitF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointerGetDescription = "$s7XamGlue43unsafeMutableRawBufferPointerGetDescription6retval4thisySpySSG_SpySwGtF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointerGetCount = "$s7XamGlue34unsafeMutableRawBufferPointerCount4thisSiSpySwG_tF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointerGetAt = "$s7XamGlue34unsafeMutableRawBufferPointerGetAt4this5indexs5UInt8VSpySwG_SitF";
		[SymbolicatorInfo (Skip = true)]
		internal const string UnsafeMutableRawBufferPointerSetAt = "$s7XamGlue33unsafeMutableRawBufferPinterSetAt4this5index5valueySpySwG_Sis5UInt8VtF";


		// Hasher
		[SymbolicatorInfo (Skip = true)]
		internal const string HasherNew = "$s7XamGlue9hasherNew6retvalySpys6HasherVG_tF";
		[SymbolicatorInfo (Skip = true)]
		internal const string HasherCombine0 = "$s7XamGlue13hasherCombine4this5thingySpys6HasherVG_xtSHRzlF";
		[SymbolicatorInfo (Skip = true)]
		internal const string HasherCombine1 = "$s7XamGlue13hasherCombine4this5bytesySpys6HasherVG_SPySWGtF";
		[SymbolicatorInfo (Skip = true)]
		internal const string HasherFinalize = "$s7XamGlue14hasherFinalize4thisSiSpys6HasherVG_tF";

		// Date
		internal const string DateNew = "$s7XamGlue7dateNew6retvalySpy10Foundation4DateVG_tF";
		internal const string DateNewFromNSDate = "$s7XamGlue17dateNewFromNSDate6retval4fromySpy10Foundation4DateVG_So0F0CtF";
		internal const string DateNewFromInterval = "$s7XamGlue19dateNewFromInterval6retval04timeF8SinceNowySpy10Foundation4DateVG_SdtF";
		internal const string DateNewSince1970 = "$s7XamGlue16dateNewSince19706retval012timeIntervalE0ySpy10Foundation4DateVG_SdtF";
		internal const string DateNewIntervalSince = "$s7XamGlue24dateNewFromIntervalSince6retval04timeF05sinceySpy10Foundation4DateVG_SdSPyAHGtF";
		internal const string DateNewIntervalSinceDate = "$s7XamGlue21dateNewSinceReference6retval012timeIntervaleF4DateySpy10Foundation0J0VG_SdtF";
		internal const string DateToNSDate = "$s7XamGlue12dateToNSDate4thisSo0E0CSpy10Foundation4DateVG_tF";

		// EveryProtocol
		[SymbolicatorInfo (Skip = true)]
		internal const string EveryProtocol_MetadataAccessor = "$s7XamGlue13EveryProtocolCMa";
		[SymbolicatorInfo (Skip = true)]
		internal const string EveryProtocolNew = "$s7XamGlue13EveryProtocolCACycfC";

	}
}

